[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "starlenz-bot"
envVars = [
    "TELEGRAM_TOKEN",
    "ANTHROPIC_API_KEY",
    "PORT"
]
